### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by denzerdhard** [linuxdeepin/deepin-image-viewer#1]
It would be nice if sorting order followed deepin-file-manager sorting order when user opens image from it.

**Comment by fasheng** [comment]
OK, thanks for the advice.
@dragondjf @hualet @Match-Yang

**Comment by DmitrySkibitsky** [comment]
Unfortunately, it was never implemented

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
