### ISSUE TITLE
Deepin Image viewer is incompatible with krita

### ISSUE THREAD

**Issue by Makogan** [linuxdeepin/deepin-image-viewer#10]
I love your work guys, but you are breaking krita somehow. Krita throws a segmentation fault if deepin imag viewer is also isntalled, so you should probably try to correct that. I won't be able to use deepin-image-viewer until that bug is fixed since krita is more critical to me than deepin, but I would like to ahve them both.

**Comment by pangpangpang3** [comment]
Now, it's compatible now, you can try it again.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
