### ISSUE TITLE
Deepin Image Viewer no longer working ...

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-image-viewer#14]
Linking the Issue from [here](https://github.com/linuxdeepin/com.deepin.ImageViewer/issues/1) ...

If anybody facing the same issue even with Deepin Image Viewer(non-flatpak version) after installing Deepin Draw can report here ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
