### ISSUE TITLE
Deepin Image Viewer is not opening images...

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-image-viewer#15]
If I try to open an image using Deepin Image Viewer, then it doesn't open the photo!!

**Comment by aiamuzz** [comment]
already raised this issue ... linking both ...
https://github.com/linuxdeepin/deepin-image-viewer/issues/14

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
