### ISSUE TITLE
many crash and segment fault,current version, archlinux

### ISSUE THREAD

**Issue by lisuke** [linuxdeepin/deepin-image-viewer#16]
for example:
1   sqlite3DbMallocRawNN                                                                                                                                         0x7fffcb362adc 
2   ??                                                                                                                                                           0x7fffcb36db2c 
3   sqlite3Parser                                                                                                                                                0x7fffcb36ecc8 
4   sqlite3RunParser                                                                                                                                             0x7fffcb38b0b7 
5   ??                                                                                                                                                           0x7fffcb375056 
6   ??                                                                                                                                                           0x7fffcb37541e 
7   ??                                                                                                                                                           0x7fffcb375595 
8   ??                                                                                                                                                           0x7fffcb5f414c 
9   QSqlResult::savePrepare(QString const&)                                                                                                                      0x7ffff420e49a 
10  QSqlQuery::prepare(QString const&)                                                                                                                           0x7ffff41fe9e9 
11  DBManager::getImgInfos                                                                                                                dbmanager.cpp      714 0x555555663094 
12  DBManager::getInfoByPathHash                                                                                                          dbmanager.cpp      169 0x55555565d791 
13  DBManager::getAlbumInfo                                                                                                               dbmanager.cpp      425 0x55555566019e 
14  TopAlbumTips::setAlbum                                                                                                                topalbumtips.cpp   45  0x5555555cd2b9 
15  ImagesView::initItems                                                                                                                 imagesview.cpp     456 0x5555555c5cce 
16  ImagesView::setAlbum                                                                                                                  imagesview.cpp     118 0x5555555c3738 
17  AlbumPanel::onOpenAlbum                                                                                                               albumpanel.cpp     468 0x5555555b6822 
18  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QString const&>, void, void (AlbumPanel:: *)(QString const&)>::call qobjectdefs_impl.h 136 0x5555555bbce6 
19  QtPrivate::FunctionPointer<void (AlbumPanel:: *)(QString const&)>::call<QtPrivate::List<QString const&>, void>                        qobjectdefs_impl.h 169 0x5555555bb7d9 
20  QtPrivate::QSlotObject<void (AlbumPanel:: *)(QString const&), QtPrivate::List<QString const&>, void>::impl                            qobjectdefs_impl.h 398 0x5555555bb181 
... <更多>

**Comment by lisuke** [comment]
@felixonmars @hualet

**Comment by lisuke** [comment]
[corefile.zip](https://github.com/linuxdeepin/deepin-image-viewer/files/1832188/corefile.zip)
@hualet

**Comment by lisuke** [comment]
sqlite3 --version
3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2171d

**Comment by lisuke** [comment]
This issue may be a  thread-safety problem. @hualet 
https://bugreports.qt.io/browse/QTBUG-66827
https://github.com/qt/qtbase/commit/610a9e8f319eafcbcf193e4b90119a6f89d0caf9#diff-6f8f1d6b4a2d9180b211f8fb09eeaf88

**Comment by hualet** [comment]
then this should be an arch-specific issue ? @felixonmars

**Comment by felixonmars** [comment]
The Qt bug was closed as invalid, saying this should be fixed in the client source. @hualet
