### ISSUE TITLE
Symbol lookup error: /usr/lib/libfreeimage.so.3

### ISSUE THREAD

**Issue by FrozenMind** [linuxdeepin/deepin-image-viewer#18]
whenever i run deepin, it returns this error:
```
deepin-image-viewer: symbol lookup error: /usr/lib/libfreeimage.so.3: undefined symbol: _ZTIN7Iex_2_27BaseExcE
```

I already tried rebooting, reinstalling, uninstall and install.

The file ```/usr/lib/libfreeimage.so.3``` exists as link:

```
lrwxrwxrwx   1 root root    22 Jun  9 17:25 libfreeimage.so.3 -> libfreeimage-3.17.0.so*
```

```libfreeimage-3.17.0.so*``` also exists.

Is it a file from deepin? so i can remove it and it becomes recreated on install?

**Comment by Guptajakala** [comment]
@FrozenMind I have met the same problem. Did you solve it?
