### ISSUE TITLE
the freeimage qimagio plugin is broken

### ISSUE THREAD

**Issue by boudewijnrempt** [linuxdeepin/deepin-image-viewer#2]
When people install deepin, other Qt applications will suddenly start crashing for them because the freeimage plugin is broken:

https://www.google.nl/search?q=deepin+qimageio&ie=UTF-8&gws_rd=cr&ei=SMKAWNSjKMf7aoOXlrgI

**Comment by Algorithmus** [comment]
I found the fix. In freeimagehandler.cpp, one of the previous commits removed a check for bytes available around line 32 (36 in master):
if (quid->isOpen() && quid->bytesAvailable() > 0)

so now it just requires quid->isOpen(). If you put the bytes available check back in there, it works.
Unfortunately, I haven't played around enough with the image viewer, so I'm unsure what the implications for this are.

**Comment by boudewijnrempt** [comment]
Doing the check is always the right thing, I would say.

**Comment by pangpangpang3** [comment]
The reason why we get rid of this check is for the sake of more compatible format, if join this judgment, part of the format of the picture will not be able to identify;
As for why the causes of the collapse of plug-in is still in search.

**Comment by alvinhochun** [comment]
Just jumping in, I took a quick peek and found this: https://github.com/linuxdeepin/deepin-image-viewer/blob/40c772d9680db2e8d8487e36faaa8cad6dee761b/qimage-plugins/freeimage/freeimagehandler.cpp#L47

That's definitely broken as hell. Probably should've been `QIODevice::size()`. Fix this crap and try again.

**Comment by nyancat18** [comment]
i got the same issue with krita

**Comment by boudewijnrempt** [comment]
To repeat: this isn't an issue with krita. This plugin is completely broken. It is also superfluous: it should not exist. Deepin should just recommend people to install the kiamgeformats (https://phabricator.kde.org/source/kimageformats/) plugins, and stop developing this plugin.

**Comment by smurfix** [comment]
Is there any resolution to this problem, or does Krita et al. still die a messy death when they see zero-byte "JPEG" files?

**Comment by boudewijnrempt** [comment]
On donderdag 13 december 2018 21:49:01 CET Matthias Urlichs wrote:
> Is there any resolution to this problem, or does Krita et al. still die a
> messy death when they see zero-byte "JPEG" files?

We replaced the reference images docker with a different thing, but as far as 
I know, the deepin people still haven't fixed their bug.
-- 
https://www.valdyas.org | https://www.krita.org

**Comment by boudewijnrempt** [comment]
We got an "interesting" new bug report today because of this asinine plugin: https://bugs.kde.org/show_bug.cgi?id=405730

There is NO reason WHATSOEVER for Deepin Imageviewer to have a QImageIO plugin called libxfreeimage.so (wrong name, too, it doesn't suggest it's a qimageio plugin) AT ALL. Qt already provides perfectly satisfactory JPG and PNG support. The Deepin Imageviewer would work better without this plugin. And for additional file formats, Deepin should use KimageFormats: https://api.kde.org/frameworks/kimageformats/html/index.html (which does not depends on other KDE Frameworks libraries, so no whining about that).

**Comment by hualet** [comment]
Let's give it a shot then :)

**Comment by boudewijnrempt** [comment]
Thank you, thank you, thank you!
