### ISSUE TITLE
[Feature Request] Mouse Wheel options...

### ISSUE THREAD

**Issue by momoe** [linuxdeepin/deepin-image-viewer#20]
Please make a preference setting to change mousewheel from Zoom In/Out to Previous/Next images please. 

P.S. also if you could make a 'Space' for 'Next image' and 'Shift_Space' keyboard shortcut for 'Previous Image' in viewer that would be very helpful too

**Comment by keybreak** [comment]
@aiamuzz
While i completely agree with you, Ctrl + Mouse wheel should be pretty good power-user hidden gem ;)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
