### ISSUE TITLE
Window not maximizing 

### ISSUE THREAD

**Issue by JordanVScher** [linuxdeepin/deepin-image-viewer#21]
Hello. I'm running deepin-image-viewer (1.2.22-1) on the ParrotSec distro with Mate. 
It used to work perfectly but since a few weeks ago, every time I open any image the application window is small. When I try to maximize the window the size changes but it doesn't cover all of the screen like usual. Even when I go full screen it doesn't cover everything. Everything else seems to be working fine. 
You can see what I mean here, going from full screen to minimized window: https://imgur.com/a/SEttDw5.

I have never seem this happening with any other software. 

EDIT: Forgot to add that on the config.conf file the MAINWINDOW attribute is set like this:
WindowHeight=866 and WindowWidth=720.
Changing the values there doesn't really work, it always resets to those values.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
