### ISSUE TITLE
Crashes constantly: thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0', rsvg_internals/src/surface_utils/iterators.rs:72:9

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/deepin-image-viewer#22]
It crashes constantly, rendering the app barely usable:

```
"dtkwidget2" can not find qm files
"deepin-image-viewer" can not find qm files
Deepin Image Viewer is defaultImage!
database is exist!
thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0',
rsvg_internals/src/surface_utils/iterators.rs:72:9
fatal runtime error: failed to initiate panic, error 5
```

deepin-image-viewer 1.2.23

**Comment by OmarSquircleArt** [comment]
Same here:
```
thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0', rsvg_internals/src/surface_utils/iterators.rs:78:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
On Arch, deepin-image-viewer 1.2.23-2

**Comment by SiamSami** [comment]
I am running Arch Linux and I have the same problem...

`[toor@archlinux wallpaper]$ deepin-image-viewer archlinux-simplyblack-43.png
"dtkwidget2" can not find qm files
"deepin-image-viewer" can not find qm files
Setting file: "/home/toor/.config/deepin/deepin-image-viewer/config.conf"
2018-10-17, 11:14:41.586 [Debug  ] [                                                         0] LogFile: "/home/toor/.cache/deepin/deepin-image-viewer/deepin-image-viewer.log"
2018-10-17, 11:14:41.586 [Debug  ] [                                                         0] Deepin Image Viewer is defaultImage!
2018-10-17, 11:14:41.920 [Debug  ] [                                                         0] database is exist!
thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0', rsvg_internals/src/surface_utils/iterators.rs:78:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
`

**Comment by SaQQ** [comment]
Same, on ArchLinux 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux.
deepin-image-viewer 1.3

`thread '<unnamed>' panicked at 'assertion failed: rectangle.x1 >= rectangle.x0', rsvg_internals/src/surface_utils/iterators.rs:78:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5`

Occurs every time, while clicking or even doing random mouse movements.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
