### ISSUE TITLE
Zooms in the opposite direction

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/deepin-image-viewer#25]
After opening a picture with Deepin image viewer, if we try to zoom in to a direction with the mouse wheel,
then it zooms in to the opposite direction.
![deepin-screen-recorder_deepin-image-viewer_20181024103921](https://user-images.githubusercontent.com/33563064/47406643-34b39880-d779-11e8-9f4c-320783daa0a1.gif)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
