### ISSUE TITLE
Feature Request : Transparent Background ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-image-viewer#27]
Hi,

Is it possible to make the background of this application transparent ... something similar to opacity/transparency control you have implemented in deepin-terminal ???

the album and recent view can be the same ... only the image viewer can get the transparency treatment.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
