### ISSUE TITLE
Feature Request : A film roll at the bottom displaying the other images in the same folder as the open image ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-image-viewer#28]
Hi,

It would be great to have a film roll at the bottom-center with thumbnails enabling us to move about the photos/images in a particular folder with right/left arrow keys ... currently the right/left keys do work but its like flying blind at switching ... but with the film roll with thumbnails showing at the bottom will enable faster navigation to the desired photograph/image from the collection. 

This along with the [Request for a Transparent Background](https://github.com/linuxdeepin/deepin-image-viewer/issues/27) ... would make the image viewer eye candy and more functional to browse through one's collection.

Currently its not a very enjoyable proposition visually ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
