### ISSUE TITLE
Congrats !!! ... For the first time since i moved to Deepin OS ... I am enjoying the lightening response of the Deepin image viewer

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/deepin-image-viewer#29]
Congrats !!! ... For the first time since i moved to Deepin OS ... I am enjoying the lightening response of the Deepin image viewer !!!

Until now i hated to open images as they would take forever to open simple images ... but now its lightening fast !!!

I really hope your project manager approves these 2 changes ...

[Transparent Background](https://github.com/linuxdeepin/deepin-image-viewer/issues/27)
[A film roll at the bottom](https://github.com/linuxdeepin/deepin-image-viewer/issues/28)

with these 2 features and the current lightening fast response ... i am sure this Deepin application will be a real eye candy and a treat to use !!!

**Comment by i-shubhamprakash** [comment]
Very Happy to see you liked Deepin OS. Hope you continue to enjoy using it. :smiley:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
