### ISSUE TITLE
请考虑移除对 dpkg-parsechangelog 的调用

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/deepin-image-viewer#32]
https://github.com/linuxdeepin/deepin-image-viewer/blob/b8c63818b93454f324c3d9519ace2a281d0d995b/debian/rules#L6

这里有对 dpkg-parsechangelog 的调用，dpkg 工具链已不再推荐如此使用。详情请见 https://bugs.debian.org/793404 。

请考虑使用 `/usr/share/dpkg/pkg-info.mk` 中提供的各个变量，具体来说此处可用 `DEB_VERSION_UPSTREAM`。这些变量的兼容性也很不错，至少在 Deepin 稳定版中已经出现。目前的 debian/rules 文件已经引入 `default.mk`，它包含了 `pkg-info.mk` 故无需额外工作。

这样，`debian/rules` 中可以如下编写：

```makefile
override_dh_auto_configure:
	dh_auto_configure -- DEFINES+="VERSION=$(DEB_VERSION_UPSTREAM)"
```

所有可用变量如下所示：

```
DEB_SOURCE: the source package name
DEB_VERSION: the full version of the package (epoch + upstream vers. + revision)
DEB_VERSION_EPOCH_UPSTREAM: the package's version without the Debian revision
DEB_VERSION_UPSTREAM_REVISION: the package's version without the Debian epoch
DEB_VERSION_UPSTREAM: the package's upstream version
DEB_DISTRIBUTION: the distribution(s) listed in the current entry of debian/changelog
```

**Comment by hualet** [comment]
https://cr.deepin.io/#/c/deepin-image-viewer/+/41304

**Comment by hualet** [comment]
还有好多其他项目也用了这个，我再开一个一同处理吧。

**Comment by BLumia** [comment]
应该已经处理过了，关掉了 :)
