### ISSUE TITLE
xfce桌面环境不能更换壁纸 

### ISSUE THREAD

**Issue by lowy** [linuxdeepin/deepin-image-viewer#4]
经debian编译测试 需修改deepin-image-viewer/viewer/controller/wallpapersetter.cpp 98行：
         "/backdrop/screen0/monitor0/image-path -s %1").arg(path);
改为：
        "/backdrop/screen0/monitor0/workspace0/last-image -s %1").arg(path);

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
