### ISSUE TITLE
图片查看器下方缩略图会遮挡图片

### ISSUE THREAD

**Issue by dfc643** [linuxdeepin/deepin-image-viewer#62]
图片查看器下方缩略图会遮挡图片，    
比如查看合同的时候，页码被遮挡。

![截图录屏_选择区域_20210113110219.png](https://i.loli.net/2021/01/13/qRieLO32aYK6yQ7.png)

**Comment by deepin-CD** [comment]
现在策略是在全屏的时候查看图片会隐藏工具栏，这样就不会遮挡图片底部的内容了。

**Comment by dfc643** [comment]
> 现在策略是在全屏的时候查看图片会隐藏工具栏，这样就不会遮挡图片底部的内容了。

感谢官方的回复，不过能否考虑添加选项（手动隐藏），或者鼠标放上来停留几秒钟变隐藏之类的？

**Comment by deepin-CD** [comment]
产品已纳入需求池，后期会优化。

**Comment by deepin-CD** [comment]
由于此问题一直未得到回应，先将其暂且关闭，如有新的动态请重新打开issue。
