### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by 1433223anpeng** [linuxdeepin/deepin-image-viewer#63]
我发现deepin-image-viewer不能打开不是以图片格式为后缀的图片，例如打不开1.jpg.1
bug的位置大概在/src/src/utils/imageutils.h附近因为我在这附近看到了
链接是下面这个
https://bbs.deepin.org/post/213797
这里应该修复成通过文件头来判断是不是图片，我是一个c++新手，我自己写了一丢丢代码我觉得应该差不多是这样的
`#include <iostream>
#include <fstream>
#include <string>

using namespace std;

int main(){
    string b;
    cout << "请输入文件名：";
    getline(cin,b);
    ifstream INPUT(b,ios::in | ios::binary);
    cout << "Reading from the file" << endl;
    int a = 8;
    uint64_t data ;
    uint64_t data2 = ### 0xa1a0a0d474e5089;//png文件头
    INPUT.read((char *)&data,a);
    // cout << data[0] << endl;
    cout << hex << data << endl;
    if (data == data2){
        cout << "YES" << endl;
    }
    INPUT.close();
 
   return 0;
}`
大致是这样的，这样就不会遇到后缀不对就打不开图片了
希望官方能修复这个小问题

**Comment by deepin-CD** [comment]
谢谢您的提议，后期会修复此问题，根据MimeType进行判断文件格式。

**Comment by 1433223anpeng** [comment]
谢谢你的回复，期待国产越来越好，走向世界！
加油！！




安鹏
太原科技大学


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxdeepin/deepin-image-viewer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月18日(星期四) 中午11:14
收件人:&nbsp;"linuxdeepin/deepin-image-viewer"<deepin-image-viewer@noreply.github.com&gt;;
抄送:&nbsp;"&amp;#x2661;&amp;#x2665;"<1367621299@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linuxdeepin/deepin-image-viewer] 一个小bug (#63)





 
谢谢您的提议，后期会修复此问题，根据MimeType进行判断文件格式。

**Comment by 1433223anpeng** [comment]
加油！！

**Comment by dependon** [comment]
最新的代码已经把这个修改了，感谢！，后续会集成

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
