### ISSUE TITLE
增加图片编辑入口

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/deepin-image-viewer#66]
![alt](https://i0.hdslb.com/bfs/album/ab7a96e10b295672d3a7668fa525fa54f27242ee.png)
![alt](https://i0.hdslb.com/bfs/album/0aea8a99d0d5857b33d7eca0b21d3fe5fe38b8b9.png)

**Comment by dependon** [comment]
这个后续肯定会加的
，得看产品规划效果
