### ISSUE TITLE
Deepin image viewer wont open images of hidden files that start with a dot " . "

### ISSUE THREAD

**Issue by tetration** [linuxdeepin/deepin-image-viewer#8]
When using Deepin image viewer if i try to open any kind of image extensions whether it is jpeg, bmp and others if for example i try to rename a file like  .summertrip.jpg, when opening it Deepin Image viewer wont show anything at all. However a simple workaround i found is unhiding the image file by renaming the same file as summertrip.jpg it will open up without any problems at all. However if I try to use any other kind of image viewer or other linux distributions with their default image viewer to open the same hidden image file, that starts with a dot(.), will be able to be opened by them without any problems at all. 

It looks like Deepin-image-viewer can only open hidden image files if the dot is removed from the beginning of the filename, thus making them visible files again.

**Comment by pangpangpang3** [comment]
We store image is recorded according to the path + name of the picture, if the name of the picture has changed, the path of the image has changed, it needs to be added in this picture.


If you want to monitor the change of image, add the directory where the image is located in the sync button options dialog box in the bottom toolbar.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
