### ISSUE TITLE
delete a pic ignores next pic

### ISSUE THREAD

**Issue by FrozenMind** [linuxdeepin/deepin-image-viewer#9]
Hello,
I have multiple images in one folder i.e. a, b & c.
Now I delete picture a, then deepin shows picture c instead of picture b.
So I don't see picture b when I want to zap through a folder and sort out bad pics.
Greets
Valentin :) 

edit: this happens like 80% of the time

**Comment by pangpangpang3** [comment]
It's a bug, we will fix it later.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
